# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='funcitonal',
            new_name='functional',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='testcase',
        ),
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('INI', 'Initialized'), ('DRT', 'Drafted'), ('RVW', 'Reviewed'), ('RLS', 'Released')], default='INI', max_length=3),
        ),
        migrations.AddField(
            model_name='testcase',
            name='title',
            field=models.CharField(default='dummy test case', max_length=128),
        ),
        migrations.AddField(
            model_name='teststep',
            name='action',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststep',
            name='reaction',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststep',
            name='step_type',
            field=models.CharField(choices=[('PRE', 'Pre-condition'), ('TS', 'Test-step'), ('POS', 'Post-condition')], default='TS', max_length=3),
        ),
        migrations.AddField(
            model_name='composition',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.TestCase'),
        ),
        migrations.AddField(
            model_name='composition',
            name='teststep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.TestStep'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='steps',
            field=models.ManyToManyField(through='pool.Composition', to='pool.TestStep'),
        ),
    ]
